### ISSUE TITLE
jenkinsコンテナ起動エラー

### ISSUE THREAD

**Issue by ayapapa** [ayapapa/docker-alminium#36]
エラーログは以下の通り。
```
jenkins_1   | INFO: Listed all plugins
jenkins_1   | Oct 09, 2020 11:23:52 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1   | SEVERE: Failed Loading plugin SCM API Plugin v2.6.4 (scm-api)
jenkins_1   | java.io.IOException: SCM API Plugin v2.6.4 failed to load.
jenkins_1   |  - You must update Jenkins from v2.151 to v2.176.4 or later to run
jenkins_1   |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.
jenkins_1   |   at hudson.PluginManager$2$1$1.run(PluginManager.java:511)
jenkins_1   |   at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGr
jenkins_1   |   at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1   |   at jenkins.model.Jenkins$5.runTask(Jenkins.java:1069)
jenkins_1   |   at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1   |   at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1   |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolE
jenkins_1   |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPool
jenkins_1   |   at java.lang.Thread.run(Thread.java:748)
jenkins_1   |
jenkins_1   | Oct 09, 2020 11:23:53 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1   | SEVERE: Failed Loading plugin Pipeline: API v2.40 (workflow-api)
jenkins_1   | java.io.IOException: Pipeline: API v2.40 failed to load.
jenkins_1   |  - SCM API Plugin v2.6.4 failed to load. Fix this plugin first.
jenkins_1   |   at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.
jenkins_1   |   at hudson.PluginManager$2$1$1.run(PluginManager.java:511)
jenkins_1   |   at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGr
jenkins_1   |   at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
```

**Comment by ayapapa** [comment]
Jenkinsのバージョンが古いことによる問題なので、最新版を使用するように変更する。
さらに、ALMiniumインストール時に設置される、Jenkinsのプラグインなどのインストールも、行うように更新する。

**Comment by ayapapa** [comment]
fixed.
